[package]
name = "gmm"
version = "1.1.0"
edition = "2021"
description = "Give me money! A CLI program to help you allocate money."
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["givememoney"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-table = "0.4.7"
givememoney = { path = "./givememoney"}

[workspace]
members = [
    "givememoney",
    "money",
]

[workspace.package]
repository = "https://github.com/hms5232/givememoney"
license = "Apache-2.0"
