[package]
name = "givememoney-wasm"
version = "0.1.0"
edition = "2024"
repository.workspace = true
license.workspace = true

[dependencies]
givememoney = { path = "../core" }
serde = { version = "1.0.229", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.128"

[lib]
crate-type = ["cdylib", "rlib"]
